#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Aplikasi_KOMA")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPengguna(Pengguna instance);
    partial void UpdatePengguna(Pengguna instance);
    partial void DeletePengguna(Pengguna instance);
    partial void InsertPenghuni(Penghuni instance);
    partial void UpdatePenghuni(Penghuni instance);
    partial void DeletePenghuni(Penghuni instance);
    partial void InsertKamar(Kamar instance);
    partial void UpdateKamar(Kamar instance);
    partial void DeleteKamar(Kamar instance);
    partial void InsertBackup(Backup instance);
    partial void UpdateBackup(Backup instance);
    partial void DeleteBackup(Backup instance);
    partial void InsertPembayaran(Pembayaran instance);
    partial void UpdatePembayaran(Pembayaran instance);
    partial void DeletePembayaran(Pembayaran instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.Aplikasi_KOMAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pengguna> Penggunas
		{
			get
			{
				return this.GetTable<Pengguna>();
			}
		}
		
		public System.Data.Linq.Table<Penghuni> Penghunis
		{
			get
			{
				return this.GetTable<Penghuni>();
			}
		}
		
		public System.Data.Linq.Table<Kamar> Kamars
		{
			get
			{
				return this.GetTable<Kamar>();
			}
		}
		
		public System.Data.Linq.Table<Backup> Backups
		{
			get
			{
				return this.GetTable<Backup>();
			}
		}
		
		public System.Data.Linq.Table<Pembayaran> Pembayarans
		{
			get
			{
				return this.GetTable<Pembayaran>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pengguna")]
	public partial class Pengguna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Pengguna;
		
		private string _NamaPengguna;
		
		private string _KataSandi;
		
		private string _Peran;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PenggunaChanging(int value);
    partial void OnID_PenggunaChanged();
    partial void OnNamaPenggunaChanging(string value);
    partial void OnNamaPenggunaChanged();
    partial void OnKataSandiChanging(string value);
    partial void OnKataSandiChanged();
    partial void OnPeranChanging(string value);
    partial void OnPeranChanged();
    #endregion
		
		public Pengguna()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pengguna", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Pengguna
		{
			get
			{
				return this._ID_Pengguna;
			}
			set
			{
				if ((this._ID_Pengguna != value))
				{
					this.OnID_PenggunaChanging(value);
					this.SendPropertyChanging();
					this._ID_Pengguna = value;
					this.SendPropertyChanged("ID_Pengguna");
					this.OnID_PenggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaPengguna", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NamaPengguna
		{
			get
			{
				return this._NamaPengguna;
			}
			set
			{
				if ((this._NamaPengguna != value))
				{
					this.OnNamaPenggunaChanging(value);
					this.SendPropertyChanging();
					this._NamaPengguna = value;
					this.SendPropertyChanged("NamaPengguna");
					this.OnNamaPenggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KataSandi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string KataSandi
		{
			get
			{
				return this._KataSandi;
			}
			set
			{
				if ((this._KataSandi != value))
				{
					this.OnKataSandiChanging(value);
					this.SendPropertyChanging();
					this._KataSandi = value;
					this.SendPropertyChanged("KataSandi");
					this.OnKataSandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peran", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Peran
		{
			get
			{
				return this._Peran;
			}
			set
			{
				if ((this._Peran != value))
				{
					this.OnPeranChanging(value);
					this.SendPropertyChanging();
					this._Peran = value;
					this.SendPropertyChanged("Peran");
					this.OnPeranChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Penghuni")]
	public partial class Penghuni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Penghuni;
		
		private string _Nama;
		
		private string _NoHP;
		
		private string _Alamat;
		
		private System.Nullable<int> _ID_Kamar;
		
		private System.DateTime _TanggalMasuk;
		
		private EntitySet<Pembayaran> _Pembayarans;
		
		private EntityRef<Kamar> _Kamar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PenghuniChanging(int value);
    partial void OnID_PenghuniChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnNoHPChanging(string value);
    partial void OnNoHPChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnID_KamarChanging(System.Nullable<int> value);
    partial void OnID_KamarChanged();
    partial void OnTanggalMasukChanging(System.DateTime value);
    partial void OnTanggalMasukChanged();
    #endregion
		
		public Penghuni()
		{
			this._Pembayarans = new EntitySet<Pembayaran>(new Action<Pembayaran>(this.attach_Pembayarans), new Action<Pembayaran>(this.detach_Pembayarans));
			this._Kamar = default(EntityRef<Kamar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Penghuni", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Penghuni
		{
			get
			{
				return this._ID_Penghuni;
			}
			set
			{
				if ((this._ID_Penghuni != value))
				{
					this.OnID_PenghuniChanging(value);
					this.SendPropertyChanging();
					this._ID_Penghuni = value;
					this.SendPropertyChanged("ID_Penghuni");
					this.OnID_PenghuniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoHP", DbType="NVarChar(20)")]
		public string NoHP
		{
			get
			{
				return this._NoHP;
			}
			set
			{
				if ((this._NoHP != value))
				{
					this.OnNoHPChanging(value);
					this.SendPropertyChanging();
					this._NoHP = value;
					this.SendPropertyChanged("NoHP");
					this.OnNoHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="NVarChar(255)")]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Kamar", DbType="Int")]
		public System.Nullable<int> ID_Kamar
		{
			get
			{
				return this._ID_Kamar;
			}
			set
			{
				if ((this._ID_Kamar != value))
				{
					if (this._Kamar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KamarChanging(value);
					this.SendPropertyChanging();
					this._ID_Kamar = value;
					this.SendPropertyChanged("ID_Kamar");
					this.OnID_KamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalMasuk", DbType="Date NOT NULL")]
		public System.DateTime TanggalMasuk
		{
			get
			{
				return this._TanggalMasuk;
			}
			set
			{
				if ((this._TanggalMasuk != value))
				{
					this.OnTanggalMasukChanging(value);
					this.SendPropertyChanging();
					this._TanggalMasuk = value;
					this.SendPropertyChanged("TanggalMasuk");
					this.OnTanggalMasukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Penghuni_Pembayaran", Storage="_Pembayarans", ThisKey="ID_Penghuni", OtherKey="ID_Penghuni")]
		public EntitySet<Pembayaran> Pembayarans
		{
			get
			{
				return this._Pembayarans;
			}
			set
			{
				this._Pembayarans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kamar_Penghuni", Storage="_Kamar", ThisKey="ID_Kamar", OtherKey="ID_Kamar", IsForeignKey=true)]
		public Kamar Kamar
		{
			get
			{
				return this._Kamar.Entity;
			}
			set
			{
				Kamar previousValue = this._Kamar.Entity;
				if (((previousValue != value) 
							|| (this._Kamar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kamar.Entity = null;
						previousValue.Penghunis.Remove(this);
					}
					this._Kamar.Entity = value;
					if ((value != null))
					{
						value.Penghunis.Add(this);
						this._ID_Kamar = value.ID_Kamar;
					}
					else
					{
						this._ID_Kamar = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kamar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pembayarans(Pembayaran entity)
		{
			this.SendPropertyChanging();
			entity.Penghuni = this;
		}
		
		private void detach_Pembayarans(Pembayaran entity)
		{
			this.SendPropertyChanging();
			entity.Penghuni = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kamar")]
	public partial class Kamar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Kamar;
		
		private string _NomorKamar;
		
		private string _Status;
		
		private decimal _Harga;
		
		private EntitySet<Penghuni> _Penghunis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KamarChanging(int value);
    partial void OnID_KamarChanged();
    partial void OnNomorKamarChanging(string value);
    partial void OnNomorKamarChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnHargaChanging(decimal value);
    partial void OnHargaChanged();
    #endregion
		
		public Kamar()
		{
			this._Penghunis = new EntitySet<Penghuni>(new Action<Penghuni>(this.attach_Penghunis), new Action<Penghuni>(this.detach_Penghunis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Kamar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Kamar
		{
			get
			{
				return this._ID_Kamar;
			}
			set
			{
				if ((this._ID_Kamar != value))
				{
					this.OnID_KamarChanging(value);
					this.SendPropertyChanging();
					this._ID_Kamar = value;
					this.SendPropertyChanged("ID_Kamar");
					this.OnID_KamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomorKamar", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NomorKamar
		{
			get
			{
				return this._NomorKamar;
			}
			set
			{
				if ((this._NomorKamar != value))
				{
					this.OnNomorKamarChanging(value);
					this.SendPropertyChanging();
					this._NomorKamar = value;
					this.SendPropertyChanged("NomorKamar");
					this.OnNomorKamarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga", DbType="Decimal(18,2) NOT NULL")]
		public decimal Harga
		{
			get
			{
				return this._Harga;
			}
			set
			{
				if ((this._Harga != value))
				{
					this.OnHargaChanging(value);
					this.SendPropertyChanging();
					this._Harga = value;
					this.SendPropertyChanged("Harga");
					this.OnHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kamar_Penghuni", Storage="_Penghunis", ThisKey="ID_Kamar", OtherKey="ID_Kamar")]
		public EntitySet<Penghuni> Penghunis
		{
			get
			{
				return this._Penghunis;
			}
			set
			{
				this._Penghunis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Penghunis(Penghuni entity)
		{
			this.SendPropertyChanging();
			entity.Kamar = this;
		}
		
		private void detach_Penghunis(Penghuni entity)
		{
			this.SendPropertyChanging();
			entity.Kamar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Backups")]
	public partial class Backup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Backup;
		
		private System.DateTime _TanggalBackup;
		
		private string _LokasiFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BackupChanging(int value);
    partial void OnID_BackupChanged();
    partial void OnTanggalBackupChanging(System.DateTime value);
    partial void OnTanggalBackupChanged();
    partial void OnLokasiFileChanging(string value);
    partial void OnLokasiFileChanged();
    #endregion
		
		public Backup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Backup", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Backup
		{
			get
			{
				return this._ID_Backup;
			}
			set
			{
				if ((this._ID_Backup != value))
				{
					this.OnID_BackupChanging(value);
					this.SendPropertyChanging();
					this._ID_Backup = value;
					this.SendPropertyChanged("ID_Backup");
					this.OnID_BackupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalBackup", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalBackup
		{
			get
			{
				return this._TanggalBackup;
			}
			set
			{
				if ((this._TanggalBackup != value))
				{
					this.OnTanggalBackupChanging(value);
					this.SendPropertyChanging();
					this._TanggalBackup = value;
					this.SendPropertyChanged("TanggalBackup");
					this.OnTanggalBackupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LokasiFile", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string LokasiFile
		{
			get
			{
				return this._LokasiFile;
			}
			set
			{
				if ((this._LokasiFile != value))
				{
					this.OnLokasiFileChanging(value);
					this.SendPropertyChanging();
					this._LokasiFile = value;
					this.SendPropertyChanged("LokasiFile");
					this.OnLokasiFileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pembayaran")]
	public partial class Pembayaran : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Pembayaran;
		
		private System.Nullable<int> _ID_Penghuni;
		
		private System.DateTime _TanggalBayar;
		
		private System.Nullable<int> _Jumlah;
		
		private string _Keterangan;
		
		private EntityRef<Penghuni> _Penghuni;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PembayaranChanging(int value);
    partial void OnID_PembayaranChanged();
    partial void OnID_PenghuniChanging(System.Nullable<int> value);
    partial void OnID_PenghuniChanged();
    partial void OnTanggalBayarChanging(System.DateTime value);
    partial void OnTanggalBayarChanged();
    partial void OnJumlahChanging(System.Nullable<int> value);
    partial void OnJumlahChanged();
    partial void OnKeteranganChanging(string value);
    partial void OnKeteranganChanged();
    #endregion
		
		public Pembayaran()
		{
			this._Penghuni = default(EntityRef<Penghuni>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pembayaran", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Pembayaran
		{
			get
			{
				return this._ID_Pembayaran;
			}
			set
			{
				if ((this._ID_Pembayaran != value))
				{
					this.OnID_PembayaranChanging(value);
					this.SendPropertyChanging();
					this._ID_Pembayaran = value;
					this.SendPropertyChanged("ID_Pembayaran");
					this.OnID_PembayaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Penghuni", DbType="Int")]
		public System.Nullable<int> ID_Penghuni
		{
			get
			{
				return this._ID_Penghuni;
			}
			set
			{
				if ((this._ID_Penghuni != value))
				{
					if (this._Penghuni.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PenghuniChanging(value);
					this.SendPropertyChanging();
					this._ID_Penghuni = value;
					this.SendPropertyChanged("ID_Penghuni");
					this.OnID_PenghuniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalBayar", DbType="Date NOT NULL")]
		public System.DateTime TanggalBayar
		{
			get
			{
				return this._TanggalBayar;
			}
			set
			{
				if ((this._TanggalBayar != value))
				{
					this.OnTanggalBayarChanging(value);
					this.SendPropertyChanging();
					this._TanggalBayar = value;
					this.SendPropertyChanged("TanggalBayar");
					this.OnTanggalBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah", DbType="Int")]
		public System.Nullable<int> Jumlah
		{
			get
			{
				return this._Jumlah;
			}
			set
			{
				if ((this._Jumlah != value))
				{
					this.OnJumlahChanging(value);
					this.SendPropertyChanging();
					this._Jumlah = value;
					this.SendPropertyChanged("Jumlah");
					this.OnJumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keterangan", DbType="NVarChar(255)")]
		public string Keterangan
		{
			get
			{
				return this._Keterangan;
			}
			set
			{
				if ((this._Keterangan != value))
				{
					this.OnKeteranganChanging(value);
					this.SendPropertyChanging();
					this._Keterangan = value;
					this.SendPropertyChanged("Keterangan");
					this.OnKeteranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Penghuni_Pembayaran", Storage="_Penghuni", ThisKey="ID_Penghuni", OtherKey="ID_Penghuni", IsForeignKey=true)]
		public Penghuni Penghuni
		{
			get
			{
				return this._Penghuni.Entity;
			}
			set
			{
				Penghuni previousValue = this._Penghuni.Entity;
				if (((previousValue != value) 
							|| (this._Penghuni.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Penghuni.Entity = null;
						previousValue.Pembayarans.Remove(this);
					}
					this._Penghuni.Entity = value;
					if ((value != null))
					{
						value.Pembayarans.Add(this);
						this._ID_Penghuni = value.ID_Penghuni;
					}
					else
					{
						this._ID_Penghuni = default(Nullable<int>);
					}
					this.SendPropertyChanged("Penghuni");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
